# Generated by Django 4.2.3 on 2023-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='time_of_create',
            field=models.DateField(auto_now_add=True, verbose_name='Time of Creation'),
        ),
    ]
